### ISSUE TITLE
Function calls for a non-existent variable 

### ISSUE THREAD

**Issue by JonatanBenarrochCMA** [cmagovuk/selene-core#37]
**Describe the bug**

When running the function [bool_url_does_not_contain](https://github.com/cmagovuk/selene-core/blob/ee12f22c6afb07d14ff2fddfcaeaea619a4adf55/selene/core/selenium/conditions.py#L157) it brings up the error: `TypeError: bool_url_does_not_contain() got an unexpected keyword argument 'url'`. This is because on [this line](https://github.com/cmagovuk/selene-core/blob/ee12f22c6afb07d14ff2fddfcaeaea619a4adf55/selene/core/selenium/conditions.py#L182) the function is calling the variable `url` despite the fact it doesn't exist.

**To Reproduce**

Call the function with a logger.

**Expected behavior**

No error.

**Screenshots**

**Additional context**

The function may be redundant as it just does the opposite of [bool_url_contains](https://github.com/cmagovuk/selene-core/blob/ee12f22c6afb07d14ff2fddfcaeaea619a4adf55/selene/core/selenium/conditions.py#L116).

**Comment by dayalstrub-cma** [comment]
@alexgillcma do you and @JonatanBenarrochCMA have time to pair and fix this at some point (or do we first need to figure out whether to remove - is it really redundant, or just implemented in a not DRY way?). might be nice for you Jonatan to see how we do tests, docs and releases.

**Comment by JonatanBenarrochCMA** [comment]
I have time, but @alexgillcma has just gone on A/L... It feels like a DRY situation, but maybe there's some advantage over using the `WebDriverWait.until` vs `.until_not` in this situation. Either way the non-existent variable should be removed in the meantime.

**Comment by alexgillcma** [comment]
Thanks guys - yep let's pick this up and maybe #29 at the same time if we can - @JonatanBenarrochCMA we'll set up a meeting when you're feeling better
